- name: declare variables at play level
  hosts: all
# if running on local-host, to avoid authentication
  connection: local
  vars:
    key: declaring first variable
  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: key == {{key}}